### ISSUE TITLE
Spec does not find function "to" on return value of "expect()"

### ISSUE THREAD

**Issue by allen-woods** [learn-co-curriculum/oo-person#15]
<img width="598" alt="screen shot 2019-01-30 at 2 38 19 pm" src="https://user-images.githubusercontent.com/44254256/52017626-c6c7ed00-249c-11e9-8643-7029ef55192c.png">

Also there are curly braces instead of parentheses.

**Comment by AspenJames** [comment]
I worked through this with @allen-woods in person, but to clarify here:

The curly brace syntax is proper here, because this test is written to check if the expression `person.name = "some_new_name` will raise an error. Using the parentheses as in the test above is to check the return value of `person.name`
